import { ChangeEvent, useEffect, useMemo, useRef, useState } from 'react'
import { Trip, TripExport, TripItem, SCHEMA_VERSION, Status, ItemType, sortTripItems, typeLabels, types, uid } from './types'
import { listTrips, removeTrip, saveTrip } from './storage'
import { parseDocumentText, parseEmail } from './parsers'

const zones = ['America/Toronto','Europe/Dublin','Europe/London','Pacific/Honolulu','UTC']
const blank = (type:ItemType='plan'):TripItem => ({id:uid(),type,title:'',start:new Date().toISOString().slice(0,16),timeZone:'Europe/Dublin',status:'planned'})
const dateFmt = (value:string, _zone:string, opts:Intl.DateTimeFormatOptions={}) => new Intl.DateTimeFormat(undefined,{timeZone:'UTC',weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',...opts}).format(new Date(`${value}:00Z`))
const dayFmt = (value:string) => new Intl.DateTimeFormat(undefined,{timeZone:'UTC',weekday:'short',month:'short',day:'numeric',year:'numeric'}).format(new Date(`${value}T12:00:00Z`))
const localTime = (value:string) => { const [hours,minutes]=value.slice(11,16).split(':').map(Number); return `${hours%12||12}:${String(minutes).padStart(2,'0')} ${hours<12?'AM':'PM'}` }
const durationFmt = (minutes?:number) => minutes ? `${Math.floor(minutes/60)}h ${String(minutes%60).padStart(2,'0')}m` : ''
const upgradeKnownFlights = (trip:Trip) => { let changed=false; const items=trip.items.map(item=>{if(item.provider==='Bunratty Castle & Folk Park'&&item.type==='event'&&item.allDay===undefined){changed=true;return {...item,start:'2026-07-28T12:00',timeZone:'Europe/Dublin',allDay:true,notes:'The confirmation specifies a visit date but no clock time.'}}if(item.provider!=='Air Canada'||item.type!=='flight')return item;if(item.title==='Toronto → Dublin'&&!item.end){changed=true;return {...item,start:'2026-07-18T20:50',end:'2026-07-19T08:15',endTimeZone:'Europe/Dublin',flightNumber:'AC 800',durationMinutes:385}}if(item.title==='Dublin → Toronto'&&!item.end){changed=true;return {...item,end:'2026-08-01T11:25',endTimeZone:'America/Toronto',flightNumber:'AC 801',durationMinutes:425}}return item});return changed?{...trip,items}:trip}
function validTrip(value:unknown): value is TripExport { const v=value as TripExport; return !!v && v.schemaVersion===SCHEMA_VERSION && !!v.trip && Array.isArray(v.trip.items) && typeof v.trip.name==='string' }
const updatedFmt = (value?:string) => value&&!Number.isNaN(new Date(value).getTime())?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'Unknown'
const bytesToBase64Url = (bytes:Uint8Array) => { let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'') }
const base64UrlToBytes = (value:string) => { const padded=value.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-value.length%4)%4),binary=atob(padded);return Uint8Array.from(binary,char=>char.charCodeAt(0)) }
async function encodeShareTrip(value:TripExport) { const json=JSON.stringify(value),bytes=new TextEncoder().encode(json);if('CompressionStream' in window){try{const stream=new Blob([bytes]).stream().pipeThrough(new CompressionStream('gzip'));return `g.${bytesToBase64Url(new Uint8Array(await new Response(stream).arrayBuffer()))}`}catch{/* Fall back to an uncompressed link on browsers with incomplete stream support. */}}return `r.${bytesToBase64Url(bytes)}` }
async function decodeShareTrip(value:string) { const [format,payload]=value.split('.',2);if(!payload)return null;const bytes=base64UrlToBytes(payload),decoded=format==='g'&&'DecompressionStream' in window?new Uint8Array(await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer()):bytes;const parsed=JSON.parse(new TextDecoder().decode(decoded));return validTrip(parsed)?parsed.trip:null }
async function sharedTripFromLocation() { const payload=new URLSearchParams(location.hash.slice(1)).get('trip');if(!payload)return null;try{return await decodeShareTrip(payload)}catch{return null} }
async function copyText(value:string) { try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(value);return true}}catch{/* Use the compatibility path below. */}const field=document.createElement('textarea');field.value=value;field.readOnly=true;field.style.position='fixed';field.style.opacity='0';document.body.append(field);field.select();field.setSelectionRange(0,value.length);try{return document.execCommand('copy')}catch{return false}finally{field.remove()} }

export default function App(){
 const [trips,setTrips]=useState<Trip[]>([]),[active,setActive]=useState<Trip|null>(null),[filter,setFilter]=useState<ItemType|'all'>('all'),[editing,setEditing]=useState<TripItem|null>(null),[drafts,setDrafts]=useState<TripItem[]>([]),[importText,setImportText]=useState(''),[notice,setNotice]=useState(''),[shareUrl,setShareUrl]=useState(''),[showImport,setShowImport]=useState(false),[mobileMenu,setMobileMenu]=useState<'none'|'trips'|'more'>('none'); const fileRef=useRef<HTMLInputElement>(null),shareRef=useRef<HTMLInputElement>(null)
 useEffect(()=>{Promise.all([listTrips(),sharedTripFromLocation()]).then(([found,shared])=>{if(shared){const snapshot={...shared,id:uid(),items:sortTripItems(shared.items)};setTrips([snapshot,...found]);setActive(snapshot);setNotice(`Opened shared snapshot updated ${updatedFmt(snapshot.updatedAt)}.`);return}const now=new Date().toISOString();const fresh=():Trip=>({id:uid(),name:'New Trip',destination:'',createdAt:now,updatedAt:now,items:[]});if(!found.length){const trip=fresh();saveTrip(trip).then(()=>{setTrips([trip]);setActive(trip)})}else if(found.length===1&&found[0].name==='Ireland summer escape'){const trip=fresh();removeTrip(found[0].id).then(()=>saveTrip(trip)).then(()=>{setTrips([trip]);setActive(trip)})}else{const upgraded=found.map(upgradeKnownFlights);Promise.all(upgraded.filter((trip,index)=>trip!==found[index]).map(saveTrip)).then(()=>{setTrips(upgraded);setActive(upgraded[0])})}})},[])
 const persist=async(next:Trip)=>{const ordered={...next,updatedAt:new Date().toISOString(),items:sortTripItems(next.items)};await saveTrip(ordered);setActive(ordered);setTrips(await listTrips())}
 const newTrip=async()=>{const now=new Date().toISOString();const trip={id:uid(),name:'New Trip',destination:'',createdAt:now,updatedAt:now,items:[]};await persist(trip);setNotice('New trip created. Give it a name and start planning.')}
 const sorted=useMemo(()=>sortTripItems(active?.items.filter(i=>filter==='all'||i.type===filter)||[]),[active,filter])
 const groups=useMemo(()=>{const days=new Map<string,TripItem[]>();for(const item of sorted){const key=item.start.slice(0,10);days.set(key,[...(days.get(key)||[]),item])}return [...days.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([day,items])=>[day,sortTripItems(items)] as const)},[sorted])
 const conflicts=new Set(sorted.flatMap((a,ai)=>sorted.slice(ai+1).filter(b=>a.end&&new Date(a.end)>new Date(b.start)&&a.timeZone===b.timeZone).flatMap(b=>[a.id,b.id])))
 const saveItem=async(item:TripItem)=>{if(!active||!item.title.trim())return;const exists=active.items.some(i=>i.id===item.id);await persist({...active,items:exists?active.items.map(i=>i.id===item.id?item:i):[...active.items,item]});setEditing(null)}
 const deleteItem=async(id:string)=>{if(active&&confirm('Delete this item?')){if(active.items.some(item=>item.id===id))await persist({...active,items:active.items.filter(item=>item.id!==id)});setDrafts(current=>current.filter(item=>item.id!==id));setEditing(null)}}
 const addDrafts=async()=>{if(!active||!drafts.length)return;await persist({...active,items:[...active.items,...drafts]});setDrafts([]);setShowImport(false);setNotice(`${drafts.length} item${drafts.length===1?'':'s'} added. You can edit anything below.`)}
 const readEmail=async(raw:string)=>{const r=parseEmail(raw);setDrafts(r.drafts);setNotice(`${r.provider}: ${r.drafts.length} draft item${r.drafts.length===1?'':'s'} ready to review.`)}
 const importFile=async(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;try{if(f.type==='application/pdf'||f.name.toLowerCase().endsWith('.pdf')){setNotice(`Reading ${f.name} locally…`);const {extractPdfText}=await import('./pdf');const text=await extractPdfText(f);if(text.trim().length<20)throw new Error('This PDF has no readable text. It may be a scanned image.');const r=parseDocumentText(text,f.name);setDrafts(r.drafts);setNotice(`PDF import: ${r.drafts.length} draft item${r.drafts.length===1?'':'s'} ready to review.`)}else await readEmail(await f.text())}catch(error){setDrafts([]);setNotice(error instanceof Error?error.message:'The document could not be read.')}e.target.value=''}
 const exportTrip=()=>{if(!active)return; const text=JSON.stringify({schemaVersion:SCHEMA_VERSION,exportedAt:new Date().toISOString(),trip:{...active,items:sortTripItems(active.items)}},null,2);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=`${active.name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()||'trip'}.json`;a.click();URL.revokeObjectURL(a.href)}
 const shareTrip=async()=>{if(!active)return;try{const payload=await encodeShareTrip({schemaVersion:SCHEMA_VERSION,exportedAt:new Date().toISOString(),trip:{...active,items:sortTripItems(active.items)}}),url=new URL(location.href);url.hash=`trip=${payload}`;const value=url.toString();setShareUrl(value);setMobileMenu('none');setNotice(await copyText(value)?`Share link copied. Snapshot updated ${updatedFmt(active.updatedAt)}.`:'Share link ready below. Select it and use your browser’s Copy command.')}catch{setNotice('This browser could not create the share link.')}}
 const importJson=async(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;try{const data=JSON.parse(await f.text());if(!validTrip(data))throw Error();const trip={...data.trip,id:uid(),name:`${data.trip.name} (imported)`,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await persist(trip);setNotice('Trip imported as a separate copy.')}catch{setNotice('That file is not a supported Waypoint trip export.')}e.target.value=''}
 if(!active)return <main className="loading">Opening your local trip library…</main>
 return <main><header><div><p className="eyebrow">WAYPOINT · LOCAL TRAVEL PLANNER</p><h1>{active.name}</h1><p className="destination"><span className="updated">Last updated {updatedFmt(active.updatedAt)}</span></p></div><div className="actions"><button className="secondary" onClick={newTrip}>+ New trip</button><button className="secondary" onClick={shareTrip}>Share trip</button><button className="secondary" onClick={exportTrip}>Export JSON</button><label className="secondary file">Import JSON<input type="file" accept="application/json" onChange={importJson}/></label><button onClick={()=>setShowImport(!showImport)}>Import email</button></div></header>
 <div className="mobile-header"><button className="icon-button" aria-label="Choose trip" onClick={()=>setMobileMenu('trips')}>☰</button><div><span>WAYPOINT</span><strong>{active.name}</strong><small>Updated {updatedFmt(active.updatedAt)}</small></div><button className="icon-button" aria-label="Trip options" onClick={()=>setMobileMenu('more')}>•••</button></div>
 {mobileMenu!=='none'&&<div className="mobile-sheet-backdrop" onClick={()=>setMobileMenu('none')}><section className="mobile-sheet" onClick={e=>e.stopPropagation()}>{mobileMenu==='trips'?<><div className="sheet-heading"><h2>Your trips</h2><button className="close" onClick={()=>setMobileMenu('none')}>×</button></div><div className="mobile-trip-list">{trips.map(trip=><button key={trip.id} className={trip.id===active.id?'active-trip':''} onClick={()=>{setActive(trip);setMobileMenu('none')}}><strong>{trip.name}</strong><span>{trip.destination||'No destination yet'}</span></button>)}</div><button onClick={()=>{newTrip();setMobileMenu('none')}}>+ New trip</button></>:<><div className="sheet-heading"><h2>Trip settings</h2><button className="close" onClick={()=>setMobileMenu('none')}>×</button></div><p className="sheet-updated">Last updated {updatedFmt(active.updatedAt)}</p><label>Trip name<input value={active.name} onChange={e=>persist({...active,name:e.target.value})}/></label><label>Destination<input value={active.destination} onChange={e=>persist({...active,destination:e.target.value})}/></label><button onClick={shareTrip}>Copy share link</button><div className="sheet-actions"><button className="secondary" onClick={exportTrip}>Export JSON</button><label className="secondary file">Import JSON<input type="file" accept="application/json" onChange={importJson}/></label></div><button className="danger" onClick={async()=>{if(confirm(`Delete ${active.name}?`)){await removeTrip(active.id);const remain=await listTrips();setTrips(remain);setActive(remain[0]||null);setMobileMenu('none')}}}>Delete trip</button></>}</section></div>}
 {notice&&<p className="notice">{notice}<button onClick={()=>setNotice('')}>×</button></p>}
 <section className="tripbar"><label>Trip<select value={active.id} onChange={e=>setActive(trips.find(t=>t.id===e.target.value)||active)}>{trips.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Name<input value={active.name} onChange={e=>persist({...active,name:e.target.value})}/></label><label>Destination<input value={active.destination} onChange={e=>persist({...active,destination:e.target.value})}/></label><button className="danger" onClick={async()=>{if(confirm(`Delete ${active.name}?`)){await removeTrip(active.id);const remain=await listTrips();setTrips(remain);setActive(remain[0]||null)}}}>Delete trip</button></section>
 {showImport&&<section className="importer"><div><h2>Import a confirmation</h2><p>Paste an email, or upload an <code>.eml</code> or text-based <code>.pdf</code> file. Processing happens entirely on this device, and the source document is discarded after drafts are made.</p><textarea value={importText} onChange={e=>setImportText(e.target.value)} placeholder="Paste reservation email text here…"/><div className="actions"><button onClick={()=>readEmail(importText)} disabled={!importText.trim()}>Parse pasted email</button><label className="secondary file">Upload email or PDF<input ref={fileRef} type="file" accept="message/rfc822,.eml,text/plain,application/pdf,.pdf" onChange={importFile}/></label></div></div>{drafts.length>0&&<div className="review"><h3>Review drafts</h3>{drafts.map(d=><button className="draft" key={d.id} onClick={()=>setEditing(d)}>{typeLabels[d.type]} · {d.title}<span>{dateFmt(d.start,d.timeZone)}</span></button>)}<button onClick={addDrafts}>Add {drafts.length} to {active.name}</button></div>}</section>}
 <nav className="filters"><button className={filter==='all'?'selected':''} onClick={()=>setFilter('all')}>All</button>{types.map(t=><button key={t} className={filter===t?'selected':''} onClick={()=>setFilter(t)}>{typeLabels[t]}</button>)}</nav>
 <section className="agenda"><div className="agenda-head"><div><p className="eyebrow">DAILY AGENDA</p><h2>{active.destination||'Your itinerary'}</h2></div><button onClick={()=>setEditing(blank())}>+ Add plan</button></div>{groups.length===0?<div className="empty">No items yet. Add a plan item or import a confirmation.</div>:groups.map(([day,items])=><div className="day" key={day}><h3>{dayFmt(day)}</h3>{items.map(item=><article className={`item ${item.type}`} key={item.id} onClick={()=>setEditing(item)}><div className="time">{item.allDay?'Time not specified':item.type==='flight'?<><span>{localTime(item.start)}</span>{item.end&&<span className="arrival-time">→ {localTime(item.end)}</span>}</>:dateFmt(item.start,item.timeZone,{weekday:undefined,month:undefined,day:undefined})}<small>{item.type==='flight'&&item.end?'departure · arrival':item.timeZone.split('/').pop()?.replace('_',' ')}</small></div><div className="item-main"><span className="pill">{typeLabels[item.type]}</span><h4>{item.title}{conflicts.has(item.id)&&<em title="Overlaps another item">Overlap</em>}</h4><p>{item.provider&&`${item.provider} · `}{item.location}{item.endLocation&&` → ${item.endLocation}`}</p>{item.type==='flight'&&(item.flightNumber||item.durationMinutes)&&<p className="flight-meta">{item.flightNumber}{item.flightNumber&&item.durationMinutes&&' · '}{durationFmt(item.durationMinutes)}</p>}{item.link&&<a className="booking-link" href={item.link} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}>Open booking ↗</a>}</div>{item.confirmation&&<span className="confirmation" title="Confirmation or ticket reference">{item.confirmation}</span>}</article>)}</div>)}</section>
 <nav className="mobile-nav"><button onClick={()=>{setFilter('all');setMobileMenu('none')}}><span>☷</span>Agenda</button><button onClick={()=>setMobileMenu('trips')}><span>▣</span>Trips</button><button className="mobile-add" onClick={()=>setEditing(blank())}><span>＋</span>Add</button><button onClick={()=>{setShowImport(true);setMobileMenu('none')}}><span>⇩</span>Import</button></nav>
 {shareUrl&&<div className="modal-backdrop" onMouseDown={()=>setShareUrl('')}><section className="modal share-dialog" onMouseDown={e=>e.stopPropagation()}><div className="modal-title"><h2>Share this trip</h2><button type="button" className="close" onClick={()=>setShareUrl('')}>×</button></div><p>This link contains the complete trip snapshot updated {updatedFmt(active.updatedAt)}.</p><label>Share link<input ref={shareRef} readOnly value={shareUrl} onFocus={e=>e.currentTarget.select()}/></label><div className="modal-actions"><a href={shareUrl} target="_blank" rel="noreferrer">Open link</a><span/><button type="button" className="secondary" onClick={()=>setShareUrl('')}>Done</button><button type="button" onClick={async()=>{shareRef.current?.select();setNotice(await copyText(shareUrl)?'Share link copied.':'Select the link and use your browser’s Copy command.')}}>Copy link</button></div></section></div>}
 {editing&&<ItemModal item={editing} onClose={()=>setEditing(null)} onSave={saveItem} onDelete={()=>deleteItem(editing.id)}/>}
 </main>
}

function ItemModal({item,onClose,onSave,onDelete}:{item:TripItem,onClose:()=>void,onSave:(i:TripItem)=>void,onDelete:()=>void}){const [v,setV]=useState(item);const field=(key:keyof TripItem)=>(e:ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setV({...v,[key]:e.target.value});return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal" onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();onSave(v)}}><div className="modal-title"><h2>{item.title?'Edit item':'Add item'}</h2><button type="button" className="close" onClick={onClose}>×</button></div><label>Type<select value={v.type} onChange={field('type')}>{types.map(t=><option value={t} key={t}>{typeLabels[t]}</option>)}</select></label><label>Title<input required value={v.title} onChange={field('title')}/></label><div className="two"><label>Starts<input type="datetime-local" value={v.start} onChange={field('start')}/></label><label>Ends<input type="datetime-local" value={v.end||''} onChange={field('end')}/></label></div>{v.type==='event'&&<label className="checkbox-label"><input type="checkbox" checked={!!v.allDay} onChange={e=>setV({...v,allDay:e.target.checked})}/> Time not specified</label>}<label>Departure time zone<select value={v.timeZone} onChange={field('timeZone')}>{zones.map(z=><option key={z}>{z}</option>)}</select></label><div className="two"><label>Provider<input value={v.provider||''} onChange={field('provider')}/></label><label>Confirmation<input value={v.confirmation||''} onChange={field('confirmation')}/></label></div>{v.type==='flight'&&<><div className="two"><label>Flight number<input value={v.flightNumber||''} onChange={field('flightNumber')}/></label><label>Duration (minutes)<input type="number" min="0" value={v.durationMinutes||''} onChange={e=>setV({...v,durationMinutes:e.target.value?Number(e.target.value):undefined})}/></label></div><label>Arrival time zone<select value={v.endTimeZone||v.timeZone} onChange={field('endTimeZone')}>{zones.map(z=><option key={z}>{z}</option>)}</select></label></>}<label>Location<input value={v.location||''} onChange={field('location')}/></label><label>End location<input value={v.endLocation||''} onChange={field('endLocation')}/></label><label>Ticket / booking link<input type="url" value={v.link||''} onChange={field('link')}/></label><label>Status<select value={v.status} onChange={field('status')}><option value="confirmed">Confirmed</option><option value="pending">Pending</option><option value="planned">Planned</option></select></label><label>Notes<textarea value={v.notes||''} onChange={field('notes')}/></label><div className="modal-actions">{item.title&&<button type="button" className="danger" onClick={onDelete}>Delete</button>}<span/><button type="button" className="secondary" onClick={onClose}>Cancel</button><button>Save item</button></div></form></div>}
