type ConfirmationLanguage='en'|'de'|'el'|'es'|'fr'|'is'|'it'|'jp'|'xx'

export const confirmationRefinements:Record<ConfirmationLanguage,Record<string,string>>={
  en:{},
  de:{'Code 128 barcode':'Code-128-Barcode','QR code':'QR-Code','Confirmation {value}. Enlarge code. Double click or double tap to show {format}':'Bestätigung {value}. Code vergrößern. Doppelklicken oder doppeltippen, um {format} anzuzeigen','Confirmation {value}. Return to item view. Double click or double tap to show {format}':'Bestätigung {value}. Zur Eintragsansicht zurückkehren. Doppelklicken oder doppeltippen, um {format} anzuzeigen','Click or tap to enlarge. Double click or double tap to show {format}.':'Zum Vergrößern klicken oder tippen. Doppelklicken oder doppeltippen, um {format} anzuzeigen.','Click or tap to return to the item view. Double click or double tap to show {format}.':'Klicken oder tippen, um zur Eintragsansicht zurückzukehren. Doppelklicken oder doppeltippen, um {format} anzuzeigen.'},
  el:{'Code 128 barcode':'γραμμωτό κώδικα Code 128','QR code':'κωδικό QR','Confirmation {value}. Enlarge code. Double click or double tap to show {format}':'Επιβεβαίωση {value}. Μεγέθυνση κωδικού. Κάντε διπλό κλικ ή διπλό πάτημα για εμφάνιση {format}','Confirmation {value}. Return to item view. Double click or double tap to show {format}':'Επιβεβαίωση {value}. Επιστροφή στην προβολή στοιχείου. Κάντε διπλό κλικ ή διπλό πάτημα για εμφάνιση {format}','Click or tap to enlarge. Double click or double tap to show {format}.':'Κάντε κλικ ή πατήστε για μεγέθυνση. Κάντε διπλό κλικ ή διπλό πάτημα για εμφάνιση {format}.','Click or tap to return to the item view. Double click or double tap to show {format}.':'Κάντε κλικ ή πατήστε για επιστροφή στην προβολή στοιχείου. Κάντε διπλό κλικ ή διπλό πάτημα για εμφάνιση {format}.'},
  es:{'Code 128 barcode':'código de barras Code 128','QR code':'código QR','Confirmation {value}. Enlarge code. Double click or double tap to show {format}':'Confirmación {value}. Ampliar código. Haz doble clic o toca dos veces para mostrar {format}','Confirmation {value}. Return to item view. Double click or double tap to show {format}':'Confirmación {value}. Volver a la vista del elemento. Haz doble clic o toca dos veces para mostrar {format}','Click or tap to enlarge. Double click or double tap to show {format}.':'Haz clic o toca para ampliar. Haz doble clic o toca dos veces para mostrar {format}.','Click or tap to return to the item view. Double click or double tap to show {format}.':'Haz clic o toca para volver a la vista del elemento. Haz doble clic o toca dos veces para mostrar {format}.'},
  fr:{'Code 128 barcode':'code-barres Code 128','QR code':'code QR','Confirmation {value}. Enlarge code. Double click or double tap to show {format}':'Confirmation {value}. Agrandir le code. Double-cliquez ou touchez deux fois pour afficher {format}','Confirmation {value}. Return to item view. Double click or double tap to show {format}':'Confirmation {value}. Revenir à l’élément. Double-cliquez ou touchez deux fois pour afficher {format}','Click or tap to enlarge. Double click or double tap to show {format}.':'Cliquez ou touchez pour agrandir. Double-cliquez ou touchez deux fois pour afficher {format}.','Click or tap to return to the item view. Double click or double tap to show {format}.':'Cliquez ou touchez pour revenir à l’élément. Double-cliquez ou touchez deux fois pour afficher {format}.'},
  is:{'Code 128 barcode':'Code 128 strikamerki','QR code':'QR-kóða','Confirmation {value}. Enlarge code. Double click or double tap to show {format}':'Staðfesting {value}. Stækka kóða. Tvísmelltu eða tvípikkaðu til að sýna {format}','Confirmation {value}. Return to item view. Double click or double tap to show {format}':'Staðfesting {value}. Fara aftur í færslusýn. Tvísmelltu eða tvípikkaðu til að sýna {format}','Click or tap to enlarge. Double click or double tap to show {format}.':'Smelltu eða pikkaðu til að stækka. Tvísmelltu eða tvípikkaðu til að sýna {format}.','Click or tap to return to the item view. Double click or double tap to show {format}.':'Smelltu eða pikkaðu til að fara aftur í færslusýn. Tvísmelltu eða tvípikkaðu til að sýna {format}.'},
  it:{'Code 128 barcode':'codice a barre Code 128','QR code':'codice QR','Confirmation {value}. Enlarge code. Double click or double tap to show {format}':'Conferma {value}. Ingrandisci codice. Fai doppio clic o doppio tocco per mostrare {format}','Confirmation {value}. Return to item view. Double click or double tap to show {format}':'Conferma {value}. Torna alla vista dell’elemento. Fai doppio clic o doppio tocco per mostrare {format}','Click or tap to enlarge. Double click or double tap to show {format}.':'Fai clic o tocca per ingrandire. Fai doppio clic o doppio tocco per mostrare {format}.','Click or tap to return to the item view. Double click or double tap to show {format}.':'Fai clic o tocca per tornare alla vista dell’elemento. Fai doppio clic o doppio tocco per mostrare {format}.'},
  jp:{'Code 128 barcode':'Code 128バーコード','QR code':'QRコード','Confirmation {value}. Enlarge code. Double click or double tap to show {format}':'確認番号 {value}。コードを拡大。ダブルクリックまたはダブルタップで{format}を表示','Confirmation {value}. Return to item view. Double click or double tap to show {format}':'確認番号 {value}。項目表示に戻る。ダブルクリックまたはダブルタップで{format}を表示','Click or tap to enlarge. Double click or double tap to show {format}.':'クリックまたはタップで拡大。ダブルクリックまたはダブルタップで{format}を表示します。','Click or tap to return to the item view. Double click or double tap to show {format}.':'クリックまたはタップで項目表示に戻ります。ダブルクリックまたはダブルタップで{format}を表示します。'},
  xx:{'Code 128 barcode':'Code 128 cargo marks','QR code':'QR rune','Confirmation {value}. Enlarge code. Double click or double tap to show {format}':'Proof {value}. Spy the code larger. Strike twice to show {format}','Confirmation {value}. Return to item view. Double click or double tap to show {format}':'Proof {value}. Return to the log entry. Strike twice to show {format}','Click or tap to enlarge. Double click or double tap to show {format}.':'Strike to spy it larger. Strike twice to show {format}.','Click or tap to return to the item view. Double click or double tap to show {format}.':'Strike to return to the log entry. Strike twice to show {format}.'},
}
