type TransientLanguage='en'|'de'|'el'|'es'|'fr'|'is'|'it'|'jp'|'xx'

export const transientRefinements:Record<TransientLanguage,Record<string,string>>={
  en:{},
  de:{'Click again to delete':'Erneut zum Löschen klicken','Deleting…':'Wird gelöscht…','Opening your local trip library…':'Lokale Reisebibliothek wird geöffnet…','Loading Google Drive trips…':'Google-Drive-Reisen werden geladen…','Restoring local copy…':'Lokale Kopie wird wiederhergestellt…','No items yet. Add an item or import Waypoint JSON.':'Noch keine Einträge. Füge einen Eintrag hinzu oder importiere Waypoint-JSON.','Google Drive is not configured for this deployment.':'Google Drive ist für diese Bereitstellung nicht konfiguriert.','Connect and show synced trips':'Verbinden und synchronisierte Reisen anzeigen'},
  el:{'Click again to delete':'Κάντε ξανά κλικ για διαγραφή','Deleting…':'Γίνεται διαγραφή…','Opening your local trip library…':'Άνοιγμα τοπικής βιβλιοθήκης ταξιδιών…','Loading Google Drive trips…':'Φόρτωση ταξιδιών από το Google Drive…','Restoring local copy…':'Επαναφορά τοπικού αντιγράφου…','No items yet. Add an item or import Waypoint JSON.':'Δεν υπάρχουν ακόμη στοιχεία. Προσθέστε ένα στοιχείο ή εισαγάγετε Waypoint JSON.','Google Drive is not configured for this deployment.':'Το Google Drive δεν έχει ρυθμιστεί για αυτή την εγκατάσταση.','Connect and show synced trips':'Σύνδεση και εμφάνιση συγχρονισμένων ταξιδιών'},
  es:{'Click again to delete':'Haz clic de nuevo para eliminar','Deleting…':'Eliminando…','Opening your local trip library…':'Abriendo tu biblioteca local de viajes…','Loading Google Drive trips…':'Cargando viajes de Google Drive…','Restoring local copy…':'Restaurando copia local…','No items yet. Add an item or import Waypoint JSON.':'Aún no hay elementos. Añade uno o importa JSON de Waypoint.','Google Drive is not configured for this deployment.':'Google Drive no está configurado para esta implementación.','Connect and show synced trips':'Conectar y mostrar viajes sincronizados'},
  fr:{'Click again to delete':'Cliquez de nouveau pour supprimer','Deleting…':'Suppression…','Opening your local trip library…':'Ouverture de votre bibliothèque locale de voyages…','Loading Google Drive trips…':'Chargement des voyages Google Drive…','Restoring local copy…':'Restauration de la copie locale…','No items yet. Add an item or import Waypoint JSON.':'Aucun élément pour le moment. Ajoutez-en un ou importez du JSON Waypoint.','Google Drive is not configured for this deployment.':'Google Drive n’est pas configuré pour ce déploiement.','Connect and show synced trips':'Se connecter et afficher les voyages synchronisés'},
  is:{'Click again to delete':'Smelltu aftur til að eyða','Deleting…':'Eyði…','Opening your local trip library…':'Opna staðbundið ferðasafn…','Loading Google Drive trips…':'Hleð ferðum úr Google Drive…','Restoring local copy…':'Endurheimti staðbundið afrit…','No items yet. Add an item or import Waypoint JSON.':'Engar færslur enn. Bættu við færslu eða flyttu inn Waypoint JSON.','Google Drive is not configured for this deployment.':'Google Drive er ekki stillt fyrir þessa útgáfu.','Connect and show synced trips':'Tengjast og sýna samstilltar ferðir'},
  it:{'Click again to delete':'Fai di nuovo clic per eliminare','Deleting…':'Eliminazione…','Opening your local trip library…':'Apertura della raccolta viaggi locale…','Loading Google Drive trips…':'Caricamento dei viaggi da Google Drive…','Restoring local copy…':'Ripristino della copia locale…','No items yet. Add an item or import Waypoint JSON.':'Nessun elemento. Aggiungine uno o importa JSON di Waypoint.','Google Drive is not configured for this deployment.':'Google Drive non è configurato per questa distribuzione.','Connect and show synced trips':'Connetti e mostra i viaggi sincronizzati'},
  jp:{'Click again to delete':'もう一度クリックして削除','Deleting…':'削除中…','Opening your local trip library…':'ローカル旅行ライブラリを開いています…','Loading Google Drive trips…':'Google Driveの旅行を読み込んでいます…','Restoring local copy…':'ローカルコピーを復元しています…','No items yet. Add an item or import Waypoint JSON.':'項目はまだありません。項目を追加するか、Waypoint JSONを読み込んでください。','Google Drive is not configured for this deployment.':'この環境ではGoogle Driveが設定されていません。','Connect and show synced trips':'接続して同期済みの旅行を表示'},
  xx:{'Click again to delete':'Strike again to scuttle','Deleting…':'Scuttlin’…','Opening your local trip library…':'Openin’ yer aboard voyage logs…','Loading Google Drive trips…':'Loadin’ Google Drive voyages…','Restoring local copy…':'Restorin’ aboard copy…','No items yet. Add an item or import Waypoint JSON.':'No log entries yet. Add one or import Waypoint JSON.','Google Drive is not configured for this deployment.':'Google Drive be not rigged for this port.','Connect and show synced trips':'Board and show synced voyages'},
}
