type TooltipLanguage='en'|'de'|'el'|'es'|'fr'|'is'|'it'|'jp'|'xx'

export const tooltipRefinements:Record<TooltipLanguage,Record<string,string>>={
 en:{},
 de:{'Expand trip route':'Reiseroute ausklappen','Collapse trip route':'Reiseroute einklappen','Trip route and destination filters':'Reiseroute und Zielfilter','Restore as local copy':'Als lokale Kopie wiederherstellen','Edit trip title':'Reisetitel bearbeiten','Trip title':'Reisetitel','Requires two clicks to delete':'Zum Löschen sind zwei Klicks erforderlich','Click again to permanently remove this trip from Waypoint':'Erneut klicken, um diese Reise dauerhaft aus Waypoint zu entfernen','Copy to clipboard':'In die Zwischenablage kopieren','Choose trip':'Reise auswählen'},
 el:{'Expand trip route':'Ανάπτυξη διαδρομής ταξιδιού','Collapse trip route':'Σύμπτυξη διαδρομής ταξιδιού','Trip route and destination filters':'Διαδρομή ταξιδιού και φίλτρα προορισμών','Restore as local copy':'Επαναφορά ως τοπικό αντίγραφο','Edit trip title':'Επεξεργασία τίτλου ταξιδιού','Trip title':'Τίτλος ταξιδιού','Requires two clicks to delete':'Απαιτούνται δύο κλικ για διαγραφή','Click again to permanently remove this trip from Waypoint':'Κάντε ξανά κλικ για οριστική αφαίρεση του ταξιδιού από το Waypoint','Copy to clipboard':'Αντιγραφή στο πρόχειρο','Choose trip':'Επιλογή ταξιδιού'},
 es:{'Expand trip route':'Expandir ruta del viaje','Collapse trip route':'Contraer ruta del viaje','Trip route and destination filters':'Ruta del viaje y filtros de destino','Restore as local copy':'Restaurar como copia local','Edit trip title':'Editar título del viaje','Trip title':'Título del viaje','Requires two clicks to delete':'Se necesitan dos clics para eliminar','Click again to permanently remove this trip from Waypoint':'Haz clic de nuevo para quitar definitivamente este viaje de Waypoint','Copy to clipboard':'Copiar al portapapeles','Choose trip':'Elegir viaje'},
 fr:{'Expand trip route':'Développer l’itinéraire du voyage','Collapse trip route':'Réduire l’itinéraire du voyage','Trip route and destination filters':'Itinéraire du voyage et filtres de destination','Restore as local copy':'Restaurer en copie locale','Edit trip title':'Modifier le titre du voyage','Trip title':'Titre du voyage','Requires two clicks to delete':'Deux clics sont nécessaires pour supprimer','Click again to permanently remove this trip from Waypoint':'Cliquez de nouveau pour supprimer définitivement ce voyage de Waypoint','Copy to clipboard':'Copier dans le presse-papiers','Choose trip':'Choisir un voyage'},
 is:{'Expand trip route':'Stækka ferðaleið','Collapse trip route':'Fella saman ferðaleið','Trip route and destination filters':'Ferðaleið og áfangastaðasíur','Restore as local copy':'Endurheimta sem staðbundið afrit','Edit trip title':'Breyta heiti ferðar','Trip title':'Heiti ferðar','Requires two clicks to delete':'Tvo smelli þarf til að eyða','Click again to permanently remove this trip from Waypoint':'Smelltu aftur til að fjarlægja ferðina varanlega úr Waypoint','Copy to clipboard':'Afrita á klemmuspjald','Choose trip':'Velja ferð'},
 it:{'Expand trip route':'Espandi itinerario del viaggio','Collapse trip route':'Comprimi itinerario del viaggio','Trip route and destination filters':'Itinerario del viaggio e filtri destinazione','Restore as local copy':'Ripristina come copia locale','Edit trip title':'Modifica titolo del viaggio','Trip title':'Titolo del viaggio','Requires two clicks to delete':'Sono necessari due clic per eliminare','Click again to permanently remove this trip from Waypoint':'Fai di nuovo clic per rimuovere definitivamente il viaggio da Waypoint','Copy to clipboard':'Copia negli appunti','Choose trip':'Scegli viaggio'},
 jp:{'Expand trip route':'旅行ルートを展開','Collapse trip route':'旅行ルートを折りたたむ','Trip route and destination filters':'旅行ルートと目的地フィルター','Restore as local copy':'ローカルコピーとして復元','Edit trip title':'旅行タイトルを編集','Trip title':'旅行タイトル','Requires two clicks to delete':'削除には2回のクリックが必要です','Click again to permanently remove this trip from Waypoint':'もう一度クリックすると、この旅行をWaypointから完全に削除します','Copy to clipboard':'クリップボードにコピー','Choose trip':'旅行を選択'},
 xx:{'Expand trip route':'Unfurl voyage course','Collapse trip route':'Roll up voyage course','Trip route and destination filters':'Voyage course and port filters','Restore as local copy':'Restore as aboard copy','Edit trip title':'Rename voyage','Trip title':'Voyage name','Requires two clicks to delete':'Two strikes be needed to scuttle','Click again to permanently remove this trip from Waypoint':'Strike again to scuttle this voyage from Waypoint forever','Copy to clipboard':'Copy to cargo board','Choose trip':'Choose a voyage'}
}
