type AccessibilityLanguage='en'|'de'|'el'|'es'|'fr'|'is'|'it'|'jp'|'xx'

export const accessibilityRefinements:Record<AccessibilityLanguage,Record<string,string>>={
  en:{},
  de:{'Trip lists':'Reiseübersichten','Show QR codes':'QR-Codes anzeigen','Itinerary weather display':'Anzeige des Reisewetters','Item editor':'Eintragseditor','No favourite trips yet. Select any star to add one.':'Noch keine favorisierten Reisen. Wähle einen Stern, um eine hinzuzufügen.','No synced trips found.':'Keine synchronisierten Reisen gefunden.','No local-only trips found.':'Keine rein lokalen Reisen gefunden.','No archived trips found.':'Keine archivierten Reisen gefunden.','Close email prompt builder':'E-Mail-Anweisungserstellung schließen'},
  el:{'Trip lists':'Λίστες ταξιδιών','Show QR codes':'Εμφάνιση κωδικών QR','Itinerary weather display':'Εμφάνιση καιρού δρομολογίου','Item editor':'Επεξεργαστής στοιχείου','No favourite trips yet. Select any star to add one.':'Δεν υπάρχουν ακόμη αγαπημένα ταξίδια. Επιλέξτε ένα αστέρι για να προσθέσετε ένα.','No synced trips found.':'Δεν βρέθηκαν συγχρονισμένα ταξίδια.','No local-only trips found.':'Δεν βρέθηκαν τοπικά ταξίδια.','No archived trips found.':'Δεν βρέθηκαν αρχειοθετημένα ταξίδια.','Close email prompt builder':'Κλείσιμο δημιουργίας οδηγιών e-mail'},
  es:{'Trip lists':'Listas de viajes','Show QR codes':'Mostrar códigos QR','Itinerary weather display':'Visualización del tiempo del itinerario','Item editor':'Editor de elementos','No favourite trips yet. Select any star to add one.':'Aún no hay viajes favoritos. Selecciona una estrella para añadir uno.','No synced trips found.':'No se encontraron viajes sincronizados.','No local-only trips found.':'No se encontraron viajes solo locales.','No archived trips found.':'No se encontraron viajes archivados.','Close email prompt builder':'Cerrar generador de instrucciones de correo'},
  fr:{'Trip lists':'Listes de voyages','Show QR codes':'Afficher les codes QR','Itinerary weather display':'Affichage de la météo de l’itinéraire','Item editor':'Éditeur d’élément','No favourite trips yet. Select any star to add one.':'Aucun voyage favori pour le moment. Sélectionnez une étoile pour en ajouter un.','No synced trips found.':'Aucun voyage synchronisé trouvé.','No local-only trips found.':'Aucun voyage local trouvé.','No archived trips found.':'Aucun voyage archivé trouvé.','Close email prompt builder':'Fermer le générateur d’instructions e-mail'},
  is:{'Trip lists':'Ferðalistar','Show QR codes':'Sýna QR-kóða','Itinerary weather display':'Birting veðurs ferðaáætlunar','Item editor':'Færsluritill','No favourite trips yet. Select any star to add one.':'Engar uppáhaldsferðir enn. Veldu stjörnu til að bæta ferð við.','No synced trips found.':'Engar samstilltar ferðir fundust.','No local-only trips found.':'Engar staðbundnar ferðir fundust.','No archived trips found.':'Engar safnaðar ferðir fundust.','Close email prompt builder':'Loka gerð tölvupóstleiðbeininga'},
  it:{'Trip lists':'Elenchi viaggi','Show QR codes':'Mostra codici QR','Itinerary weather display':'Visualizzazione meteo itinerario','Item editor':'Editor elemento','No favourite trips yet. Select any star to add one.':'Non ci sono ancora viaggi preferiti. Seleziona una stella per aggiungerne uno.','No synced trips found.':'Nessun viaggio sincronizzato trovato.','No local-only trips found.':'Nessun viaggio solo locale trovato.','No archived trips found.':'Nessun viaggio archiviato trovato.','Close email prompt builder':'Chiudi generatore istruzioni e-mail'},
  jp:{'Trip lists':'旅行一覧','Show QR codes':'QRコードを表示','Itinerary weather display':'旅程の天気表示','Item editor':'項目エディター','No favourite trips yet. Select any star to add one.':'お気に入りの旅行はまだありません。星を選択して追加してください。','No synced trips found.':'同期済みの旅行が見つかりません。','No local-only trips found.':'ローカルのみの旅行が見つかりません。','No archived trips found.':'アーカイブ済みの旅行が見つかりません。','Close email prompt builder':'メール抽出指示の作成画面を閉じる'},
  xx:{'Trip lists':'Voyage logs','Show QR codes':'Show QR runes','Itinerary weather display':'Voyage skies display','Item editor':'Log-entry editor','No favourite trips yet. Select any star to add one.':'No treasured voyages yet. Mark any star to add one.','No synced trips found.':'No synced voyages found.','No local-only trips found.':'No aboard-only voyages found.','No archived trips found.':'No stowed voyages found.','Close email prompt builder':'Close message-order builder'},
}
